"""initial schema

Revision ID: 07525a33a822
Revises: 
Create Date: 2026-07-19 01:38:20.511284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07525a33a822'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'BAILLEUR', 'LOCATAIRE', 'GESTIONNAIRE', name='userrole'), nullable=False),
    sa.Column('plan', sa.Enum('FREEMIUM', 'PREMIUM', 'AGENCE', name='plantype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('immeubles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bailleur_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('adresse', sa.String(length=500), nullable=False),
    sa.Column('ville', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bailleur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('immeuble_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('STUDIO', 'APPARTEMENT', 'MAISON', 'CHAMBRE', name='typelogement'), nullable=False),
    sa.Column('loyer_mensuel', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('statut', sa.Enum('VACANT', 'OCCUPE', name='statutlogement'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['immeuble_id'], ['immeubles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locataires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bailleur_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('logement_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('piece_identite', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bailleur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['logement_id'], ['logements.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bailleur_id', sa.Integer(), nullable=False),
    sa.Column('logement_id', sa.Integer(), nullable=False),
    sa.Column('locataire_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('loyer_mensuel', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('jour_paiement', sa.Integer(), nullable=False),
    sa.Column('depot_garantie', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('statut', sa.Enum('ACTIF', 'ARCHIVE', 'RESILIE', name='statutcontrat'), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bailleur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['locataire_id'], ['locataires.id'], ),
    sa.ForeignKeyConstraint(['logement_id'], ['logements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrat_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('periode', sa.String(length=7), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=False),
    sa.Column('mode_paiement', sa.Enum('ESPECES', 'VIREMENT', 'MOBILE_MONEY', 'AUTRE', name='modepaiement'), nullable=False),
    sa.Column('commentaire', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quittances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paiement_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=False),
    sa.Column('genere_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paiement_id'], ['paiements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero'),
    sa.UniqueConstraint('paiement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quittances')
    op.drop_table('paiements')
    op.drop_table('contrats')
    op.drop_table('locataires')
    op.drop_table('logements')
    op.drop_table('immeubles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
