"""add_contract_signature_fields

Revision ID: 7a3a40ef9bf3
Revises: a1b2c3d4e5f6
Create Date: 2026-07-26 22:49:52.563953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3a40ef9bf3'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duree_mois', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lieu_signature', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('juridiction', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('signature_bailleur_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('signature_locataire_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('EN_ATTENTE_SIGNATURE', 'ACTIF', 'ARCHIVE', 'RESILIE', name='statutcontrat'),
               existing_nullable=False)

    with op.batch_alter_table('locataires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lieu_naissance', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nationalite', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('statut_matrimonial', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nb_enfants', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cni_date_delivrance', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('cni_lieu_delivrance', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cni_lieu_delivrance')
        batch_op.drop_column('cni_date_delivrance')

    with op.batch_alter_table('locataires', schema=None) as batch_op:
        batch_op.drop_column('nb_enfants')
        batch_op.drop_column('statut_matrimonial')
        batch_op.drop_column('nationalite')
        batch_op.drop_column('lieu_naissance')

    with op.batch_alter_table('contrats', schema=None) as batch_op:
        batch_op.alter_column('statut',
               existing_type=sa.Enum('EN_ATTENTE_SIGNATURE', 'ACTIF', 'ARCHIVE', 'RESILIE', name='statutcontrat'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('signature_locataire_url')
        batch_op.drop_column('signature_bailleur_url')
        batch_op.drop_column('juridiction')
        batch_op.drop_column('lieu_signature')
        batch_op.drop_column('duree_mois')

    # ### end Alembic commands ###
